// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3xPAjAdF326--pJXBTzgJAZaZY7kGG4A',
    appId: '1:140212807073:web:6b8297180a0baa6293d7e0',
    messagingSenderId: '140212807073',
    projectId: 'hw04-97634',
    authDomain: 'hw04-97634.firebaseapp.com',
    storageBucket: 'hw04-97634.firebasestorage.app',
    measurementId: 'G-DWQDV1LJ1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh06tS6mZpxNJhfLQsoctYLgqk_Cmlj_k',
    appId: '1:140212807073:android:7fc90ed0ce2b3cc393d7e0',
    messagingSenderId: '140212807073',
    projectId: 'hw04-97634',
    storageBucket: 'hw04-97634.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCi6TTRCe5Gkfn5sXEJPSRi354I-KWg54',
    appId: '1:140212807073:ios:a0335dddbfc1737093d7e0',
    messagingSenderId: '140212807073',
    projectId: 'hw04-97634',
    storageBucket: 'hw04-97634.firebasestorage.app',
    iosClientId: '140212807073-m9vjprip2nk37mudoqtdnbntkhq6jj2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCi6TTRCe5Gkfn5sXEJPSRi354I-KWg54',
    appId: '1:140212807073:ios:a0335dddbfc1737093d7e0',
    messagingSenderId: '140212807073',
    projectId: 'hw04-97634',
    storageBucket: 'hw04-97634.firebasestorage.app',
    iosClientId: '140212807073-m9vjprip2nk37mudoqtdnbntkhq6jj2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3xPAjAdF326--pJXBTzgJAZaZY7kGG4A',
    appId: '1:140212807073:web:f223a78ec43ab56a93d7e0',
    messagingSenderId: '140212807073',
    projectId: 'hw04-97634',
    authDomain: 'hw04-97634.firebaseapp.com',
    storageBucket: 'hw04-97634.firebasestorage.app',
    measurementId: 'G-NYE9984LFK',
  );

}